// ─── Lindsay's Exercise Database ──────────────────────────────────────────────
//
// Categories:
//   squat    — back squat, front squat, and squat-pattern variations
//   hinge    — deadlift variations, RDLs, glute work
//   press    — horizontal and vertical push
//   pull     — rows, ring rows, pull-ups, curls
//   core     — carries, anti-rotation, stability
//   mobility — PT exercises, stretching, warm-up/cool-down work
//
// isAnchor: true = main lift for a session (goes heavy, programmed first)
// isAnchor: false = accessory work (supports the anchor, programmed after)
//
// Equipment options:
//   barbell, dumbbell, kettlebell, rings, band, bodyweight,
//   bench, box, landmine, sliders, foam_roller, rower, step, pull_up_bar
// ─────────────────────────────────────────────────────────────────────────────

export const EXERCISES = [

  // ── SQUAT ──────────────────────────────────────────────────────────────────

  {
    id: "ex_back_squat",
    name: "Back Squat",
    category: "squat",
    isAnchor: true,
    equipment: ["barbell"],
    muscles: ["quads", "glutes", "core"],
    defaultSets: 5,
    defaultReps: "5",
    notes: "Main anchor lift. Bar on upper traps, brace hard, sit back and down. Knees track toes.",
  },
  {
    id: "ex_front_squat",
    name: "Front Squat",
    category: "squat",
    isAnchor: true,
    equipment: ["barbell"],
    muscles: ["quads", "core", "upper_back"],
    defaultSets: 4,
    defaultReps: "5",
    notes: "Main anchor lift. Bar on front delts, elbows high. More upright torso than back squat — quad dominant.",
  },
  {
    id: "ex_box_squat",
    name: "Box Squat",
    category: "squat",
    isAnchor: false,
    equipment: ["barbell", "box"],
    muscles: ["quads", "glutes", "hamstrings"],
    defaultSets: 4,
    defaultReps: "6",
    notes: "Sit back to box, pause briefly, drive up. Great for posterior chain and depth cue.",
  },
  {
    id: "ex_pause_squat",
    name: "Pause Squat",
    category: "squat",
    isAnchor: false,
    equipment: ["barbell"],
    muscles: ["quads", "glutes", "core"],
    defaultSets: 3,
    defaultReps: "4",
    notes: "3-second pause at the bottom. Builds strength out of the hole. Keep braced throughout.",
  },
  {
    id: "ex_goblet_squat",
    name: "Goblet Squat",
    category: "squat",
    isAnchor: false,
    equipment: ["kettlebell"],
    muscles: ["quads", "glutes", "core"],
    defaultSets: 3,
    defaultReps: "12",
    notes: "Hold KB at chest. Elbows drive knees out at bottom. Great warm-up or accessory squat.",
  },
  {
    id: "ex_bulgarian_split_squat",
    name: "Bulgarian Split Squat",
    category: "squat",
    isAnchor: false,
    equipment: ["dumbbell", "bench"],
    muscles: ["quads", "glutes", "balance"],
    defaultSets: 3,
    defaultReps: "8",
    notes: "Each side. Rear foot elevated on bench. Front shin stays vertical. Brutal but effective.",
  },
  {
    id: "ex_spanish_squat",
    name: "Spanish Squat",
    category: "squat",
    isAnchor: false,
    equipment: ["band"],
    muscles: ["quads", "knees"],
    defaultSets: 3,
    defaultReps: "10",
    notes: "Joe's PT. Band around rack at shin height. Sit back and down, shins stay vertical.",
  },
  {
    id: "ex_landmine_squat",
    name: "Landmine Squat",
    category: "squat",
    isAnchor: false,
    equipment: ["landmine", "barbell"],
    muscles: ["quads", "glutes"],
    defaultSets: 3,
    defaultReps: "10",
    notes: "Hold end of landmine bar at chest. Easier on the back — good squat pattern builder.",
  },

  // ── HINGE ──────────────────────────────────────────────────────────────────

  {
    id: "ex_conventional_deadlift",
    name: "Conventional Deadlift",
    category: "hinge",
    isAnchor: true,
    equipment: ["barbell"],
    muscles: ["glutes", "hamstrings", "back", "grip"],
    defaultSets: 5,
    defaultReps: "5",
    notes: "Main anchor lift. Warm up with empty bar. Hinge at hips — not waist. Bar stays close to body.",
  },
  {
    id: "ex_sumo_deadlift",
    name: "Sumo Deadlift",
    category: "hinge",
    isAnchor: true,
    equipment: ["barbell"],
    muscles: ["glutes", "inner_thigh", "hamstrings"],
    defaultSets: 4,
    defaultReps: "5",
    notes: "Wide stance, toes out, drive knees out. More glute and inner thigh than conventional.",
  },
  {
    id: "ex_romanian_deadlift",
    name: "Romanian Deadlift (RDL)",
    category: "hinge",
    isAnchor: false,
    equipment: ["barbell"],
    muscles: ["hamstrings", "glutes", "lower_back"],
    defaultSets: 4,
    defaultReps: "8",
    notes: "Soft knee, push hips back, feel the stretch in hamstrings. Proud chest throughout.",
  },
  {
    id: "ex_kb_rdl",
    name: "KB Romanian Deadlift",
    category: "hinge",
    isAnchor: false,
    equipment: ["kettlebell"],
    muscles: ["hamstrings", "glutes"],
    defaultSets: 3,
    defaultReps: "10",
    notes: "60 lbs each hand. Same cues as barbell RDL. Good accessory when back is fatigued.",
  },
  {
    id: "ex_single_leg_rdl",
    name: "Single-Leg RDL",
    category: "hinge",
    isAnchor: false,
    equipment: ["kettlebell"],
    muscles: ["hamstrings", "glutes", "balance"],
    defaultSets: 3,
    defaultReps: "8",
    notes: "Each side. 40 lbs. Slow and controlled. Hip stays square — don't rotate.",
  },
  {
    id: "ex_good_morning",
    name: "Good Mornings",
    category: "hinge",
    isAnchor: false,
    equipment: ["barbell"],
    muscles: ["hamstrings", "glutes", "lower_back"],
    defaultSets: 3,
    defaultReps: "10",
    notes: "Keep light — 45–65 lbs. Proud chest, hinge slowly. Feels different from RDL.",
  },
  {
    id: "ex_landmine_rdl",
    name: "Landmine RDL",
    category: "hinge",
    isAnchor: false,
    equipment: ["landmine", "barbell"],
    muscles: ["hamstrings", "glutes"],
    defaultSets: 3,
    defaultReps: "10",
    notes: "Each side. Easier on the low back than barbell — good on high-fatigue days.",
  },
  {
    id: "ex_kb_deadlift",
    name: "KB Deadlift",
    category: "hinge",
    isAnchor: false,
    equipment: ["kettlebell"],
    muscles: ["glutes", "hamstrings"],
    defaultSets: 4,
    defaultReps: "8",
    notes: "80 lbs. Drive hips forward at top. Good for learning the pattern or heavy accessory.",
  },
  {
    id: "ex_glute_bridge",
    name: "Glute Bridge",
    category: "hinge",
    isAnchor: false,
    equipment: ["kettlebell"],
    muscles: ["glutes"],
    defaultSets: 3,
    defaultReps: "15",
    notes: "60 lbs KB on hips. Pause and squeeze hard at top. Drive through heels.",
  },
  {
    id: "ex_hip_thrust",
    name: "Hip Thrust",
    category: "hinge",
    isAnchor: false,
    equipment: ["barbell", "bench"],
    muscles: ["glutes", "hamstrings"],
    defaultSets: 4,
    defaultReps: "10",
    notes: "Upper back on bench, barbell across hips. Full range — from floor to lockout. Serious glute builder.",
  },
  {
    id: "ex_step_up",
    name: "Step-Up",
    category: "hinge",
    isAnchor: false,
    equipment: ["box", "dumbbell"],
    muscles: ["glutes", "quads"],
    defaultSets: 3,
    defaultReps: "10",
    notes: "Each side. Bodyweight or 20 lbs DBs. Drive through the heel of the working leg.",
  },

  // ── PRESS ──────────────────────────────────────────────────────────────────

  {
    id: "ex_barbell_bench",
    name: "Barbell Bench Press",
    category: "press",
    isAnchor: true,
    equipment: ["barbell", "bench"],
    muscles: ["chest", "triceps", "shoulders"],
    defaultSets: 5,
    defaultReps: "5",
    notes: "Main anchor — horizontal press. Retract shoulder blades. Bar to lower chest. 3-count descent.",
  },
  {
    id: "ex_barbell_ohp",
    name: "Barbell Overhead Press (OHP)",
    category: "press",
    isAnchor: true,
    equipment: ["barbell"],
    muscles: ["shoulders", "triceps", "core"],
    defaultSets: 5,
    defaultReps: "5",
    notes: "Main anchor — vertical press. Brace core hard. Bar path slightly back at top. No lower back arch.",
  },
  {
    id: "ex_db_flat_press",
    name: "Dumbbell Flat Press",
    category: "press",
    isAnchor: false,
    equipment: ["dumbbell", "bench"],
    muscles: ["chest", "triceps", "shoulders"],
    defaultSets: 4,
    defaultReps: "10",
    notes: "30–40 lbs each hand. Greater range of motion than barbell. Retract shoulder blades.",
  },
  {
    id: "ex_db_incline_press",
    name: "Dumbbell Incline Press",
    category: "press",
    isAnchor: false,
    equipment: ["dumbbell", "bench"],
    muscles: ["chest", "shoulders"],
    defaultSets: 3,
    defaultReps: "10",
    notes: "25–35 lbs each hand. Upper chest emphasis. Elbows at ~45°.",
  },
  {
    id: "ex_arnold_press",
    name: "Arnold Press",
    category: "press",
    isAnchor: false,
    equipment: ["dumbbell"],
    muscles: ["shoulders", "triceps"],
    defaultSets: 3,
    defaultReps: "10",
    notes: "20–25 lbs each hand. Full rotation through the press. Hits all three delt heads.",
  },
  {
    id: "ex_landmine_press",
    name: "Landmine Press",
    category: "press",
    isAnchor: false,
    equipment: ["landmine", "barbell"],
    muscles: ["chest", "shoulders"],
    defaultSets: 3,
    defaultReps: "10",
    notes: "Each side. Shoulder-friendly pressing angle. Keep core tight throughout.",
  },
  {
    id: "ex_tricep_dips",
    name: "Tricep Dips",
    category: "press",
    isAnchor: false,
    equipment: ["bench"],
    muscles: ["triceps", "chest"],
    defaultSets: 3,
    defaultReps: "12",
    notes: "Hands on bench, feet on floor or elevated. Keep elbows tracking back, not flaring out.",
  },
  {
    id: "ex_ring_pushups",
    name: "Ring Pushups (feet elevated)",
    category: "press",
    isAnchor: false,
    equipment: ["rings", "bench"],
    muscles: ["chest", "triceps"],
    defaultSets: 4,
    defaultReps: "8",
    notes: "Feet on bench. Rings add instability — harder than they look. Scale by lowering feet.",
  },
  {
    id: "ex_lateral_raise",
    name: "Lateral Raise",
    category: "press",
    isAnchor: false,
    equipment: ["dumbbell"],
    muscles: ["shoulders"],
    defaultSets: 3,
    defaultReps: "12",
    notes: "10–15 lbs. Slight bend in elbow. Lead with elbow, not wrist. Control the descent.",
  },
  {
    id: "ex_overhead_tricep_ext",
    name: "Overhead Tricep Extension",
    category: "press",
    isAnchor: false,
    equipment: ["dumbbell"],
    muscles: ["triceps"],
    defaultSets: 3,
    defaultReps: "12",
    notes: "25–30 lbs single dumbbell. Full range of motion. Elbows stay close to head.",
  },
  {
    id: "ex_band_tricep_pushdown",
    name: "Band Tricep Pushdown",
    category: "press",
    isAnchor: false,
    equipment: ["band", "pull_up_bar"],
    muscles: ["triceps"],
    defaultSets: 3,
    defaultReps: "15",
    notes: "Long band over pull-up bar. Elbows glued to sides. Great finisher.",
  },

  // ── PULL ───────────────────────────────────────────────────────────────────

  {
    id: "ex_barbell_row",
    name: "Barbell Bent-Over Row",
    category: "pull",
    isAnchor: true,
    equipment: ["barbell"],
    muscles: ["back", "biceps", "rear_delt"],
    defaultSets: 5,
    defaultReps: "5",
    notes: "Main anchor. Hinge to ~45°. Pull bar to lower chest. Squeeze at top. Control the descent.",
  },
  {
    id: "ex_ring_rows",
    name: "Ring Rows",
    category: "pull",
    isAnchor: true,
    equipment: ["rings"],
    muscles: ["back", "biceps", "rear_delt"],
    defaultSets: 4,
    defaultReps: "10",
    notes: "Main anchor. The more horizontal your body, the harder. 2-sec squeeze at top.",
  },
  {
    id: "ex_pull_ups",
    name: "Pull-Ups",
    category: "pull",
    isAnchor: false,
    equipment: ["pull_up_bar"],
    muscles: ["back", "biceps"],
    defaultSets: 4,
    defaultReps: "5",
    notes: "Add band if needed. Dead hang start. Drive elbows down and back.",
  },
  {
    id: "ex_db_single_arm_row",
    name: "Single-Arm Dumbbell Row",
    category: "pull",
    isAnchor: false,
    equipment: ["dumbbell", "bench"],
    muscles: ["back", "biceps"],
    defaultSets: 3,
    defaultReps: "10",
    notes: "40–50 lbs. Full stretch at bottom, drive elbow back. Don't rotate the torso.",
  },
  {
    id: "ex_landmine_row",
    name: "Landmine Row",
    category: "pull",
    isAnchor: false,
    equipment: ["landmine", "barbell"],
    muscles: ["back", "biceps"],
    defaultSets: 3,
    defaultReps: "10",
    notes: "Each side. Easier on the low back than bent-over row. Great unilateral option.",
  },
  {
    id: "ex_kb_single_arm_row",
    name: "KB Single-Arm Row",
    category: "pull",
    isAnchor: false,
    equipment: ["kettlebell"],
    muscles: ["back", "biceps"],
    defaultSets: 3,
    defaultReps: "10",
    notes: "40 lbs. Same cues as dumbbell row. Good when barbell is already loaded for something else.",
  },
  {
    id: "ex_face_pull",
    name: "Face Pull",
    category: "pull",
    isAnchor: false,
    equipment: ["band", "pull_up_bar"],
    muscles: ["rear_delt", "rotator_cuff"],
    defaultSets: 3,
    defaultReps: "15",
    notes: "Band at face height. Pull to face, elbows high and wide. Great for shoulder health.",
  },
  {
    id: "ex_rear_delt_fly",
    name: "Rear Delt Fly",
    category: "pull",
    isAnchor: false,
    equipment: ["dumbbell"],
    muscles: ["rear_delt", "upper_back"],
    defaultSets: 3,
    defaultReps: "12",
    notes: "12–15 lbs. Hinge forward slightly. Lead with elbows. Squeeze at top.",
  },
  {
    id: "ex_hammer_curl",
    name: "Hammer Curl",
    category: "pull",
    isAnchor: false,
    equipment: ["dumbbell"],
    muscles: ["biceps", "forearms"],
    defaultSets: 3,
    defaultReps: "12",
    notes: "20–25 lbs. Neutral grip. No swinging. Good for forearm and bicep development.",
  },
  {
    id: "ex_band_bicep_curl",
    name: "Band Bicep Curl",
    category: "pull",
    isAnchor: false,
    equipment: ["band"],
    muscles: ["biceps"],
    defaultSets: 3,
    defaultReps: "15",
    notes: "Short band under feet. Full range of motion. Great finisher.",
  },
  {
    id: "ex_dead_hang",
    name: "Dead Hang",
    category: "pull",
    isAnchor: false,
    equipment: ["pull_up_bar"],
    muscles: ["grip", "back"],
    defaultSets: 3,
    defaultReps: "30 sec",
    notes: "Relax shoulders fully. Decompresses the spine. Also builds grip strength passively.",
  },
  {
    id: "ex_farmer_carry",
    name: "Farmer Carry",
    category: "pull",
    isAnchor: false,
    equipment: ["kettlebell"],
    muscles: ["grip", "traps", "core"],
    defaultSets: 3,
    defaultReps: "40 steps",
    notes: "40 lbs each hand. Shoulders packed, walk tall. Underrated full-body exercise.",
  },

  // ── CORE ───────────────────────────────────────────────────────────────────

  {
    id: "ex_suitcase_carry",
    name: "Suitcase Carry",
    category: "core",
    isAnchor: false,
    equipment: ["kettlebell"],
    muscles: ["core", "obliques", "grip"],
    defaultSets: 3,
    defaultReps: "40 steps",
    notes: "40 lbs each side. Don't lean away from the weight. Brace like you're about to get poked.",
  },
  {
    id: "ex_overhead_carry",
    name: "Overhead Carry",
    category: "core",
    isAnchor: false,
    equipment: ["kettlebell"],
    muscles: ["core", "shoulders"],
    defaultSets: 3,
    defaultReps: "30 steps",
    notes: "20 lbs each side. Lock arm out. Don't shrug. Great shoulder stability + core combo.",
  },
  {
    id: "ex_dead_bug",
    name: "Dead Bug",
    category: "core",
    isAnchor: false,
    equipment: ["bodyweight"],
    muscles: ["core"],
    defaultSets: 3,
    defaultReps: "10",
    notes: "Each side. Low back pressed to floor the whole time. Exhale as you extend. Go slow.",
  },
  {
    id: "ex_pallof_press",
    name: "Pallof Press",
    category: "core",
    isAnchor: false,
    equipment: ["band"],
    muscles: ["core", "obliques"],
    defaultSets: 3,
    defaultReps: "12",
    notes: "Each side. Band at chest height. Press out and hold briefly. Fight the rotation.",
  },
  {
    id: "ex_side_plank",
    name: "Side Plank",
    category: "core",
    isAnchor: false,
    equipment: ["bodyweight"],
    muscles: ["obliques", "core"],
    defaultSets: 3,
    defaultReps: "30 sec",
    notes: "Each side. Keep hips stacked and lifted. Progress to hip dips for more challenge.",
  },
  {
    id: "ex_bird_dog",
    name: "Bird Dog",
    category: "core",
    isAnchor: false,
    equipment: ["bodyweight"],
    muscles: ["core", "lower_back"],
    defaultSets: 3,
    defaultReps: "10",
    notes: "Each side. Slow and controlled. Don't let hips rotate. Great for back health.",
  },
  {
    id: "ex_kb_windmill",
    name: "KB Windmill",
    category: "core",
    isAnchor: false,
    equipment: ["kettlebell"],
    muscles: ["core", "obliques", "shoulders"],
    defaultSets: 3,
    defaultReps: "6",
    notes: "20 lbs each side. Start light. Arm locked out overhead. Move slowly and intentionally.",
  },
  {
    id: "ex_turkish_getup",
    name: "KB Turkish Get-Up",
    category: "core",
    isAnchor: false,
    equipment: ["kettlebell"],
    muscles: ["core", "shoulders", "hips"],
    defaultSets: 3,
    defaultReps: "3",
    notes: "20 lbs each side. Each rep is a full-body check-in. Go slow — there's no rushing a TGU.",
  },
  {
    id: "ex_plank",
    name: "Plank",
    category: "core",
    isAnchor: false,
    equipment: ["bodyweight"],
    muscles: ["core"],
    defaultSets: 3,
    defaultReps: "40 sec",
    notes: "Elbows under shoulders. Squeeze glutes and abs. Don't let hips sag or pike.",
  },
  {
    id: "ex_hollow_body",
    name: "Hollow Body Hold",
    category: "core",
    isAnchor: false,
    equipment: ["bodyweight"],
    muscles: ["core"],
    defaultSets: 3,
    defaultReps: "20 sec",
    notes: "Low back pressed down. Arms and legs low but not touching floor. Exhale fully.",
  },
  {
    id: "ex_slider_knee_tucks",
    name: "Slider Knee Tucks",
    category: "core",
    isAnchor: false,
    equipment: ["sliders"],
    muscles: ["core", "hip_flexors"],
    defaultSets: 3,
    defaultReps: "10",
    notes: "Go slow. Keep hips level. Don't let low back arch as knees come in.",
  },
  {
    id: "ex_slider_pikes",
    name: "Slider Pikes",
    category: "core",
    isAnchor: false,
    equipment: ["sliders"],
    muscles: ["core", "shoulders"],
    defaultSets: 3,
    defaultReps: "8",
    notes: "Hard. Don't let hips sag in the plank position. Drive hips up in a straight line.",
  },
  {
    id: "ex_ring_body_saw",
    name: "Ring Body Saw",
    category: "core",
    isAnchor: false,
    equipment: ["rings"],
    muscles: ["core", "shoulders"],
    defaultSets: 3,
    defaultReps: "8",
    notes: "Forearms in rings, plank position. Push out and pull back. More challenge than a regular plank.",
  },
  {
    id: "ex_copenhagen_plank",
    name: "Copenhagen Plank",
    category: "core",
    isAnchor: false,
    equipment: ["bench"],
    muscles: ["core", "adductors"],
    defaultSets: 3,
    defaultReps: "20 sec",
    notes: "Each side. Top foot on bench. Keep hips level and lifted. Underrated adductor exercise.",
  },
  {
    id: "ex_slider_mountain_climbers",
    name: "Slider Mountain Climbers",
    category: "core",
    isAnchor: false,
    equipment: ["sliders"],
    muscles: ["core", "hip_flexors"],
    defaultSets: 3,
    defaultReps: "20",
    notes: "Slow and controlled — not a cardio sprint. Keep hips low and stable.",
  },

  // ── MOBILITY / PT ──────────────────────────────────────────────────────────

  {
    id: "ex_diagonal_hip_sinks",
    name: "Diagonal Hip Sinks",
    category: "mobility",
    isAnchor: false,
    equipment: ["bodyweight"],
    muscles: ["hip_flexors", "glutes"],
    defaultSets: 1,
    defaultReps: "10",
    notes: "Joe's PT. Each side. Slow and intentional. Great hip mobility warm-up.",
  },
  {
    id: "ex_midfoot_mobilization",
    name: "Midfoot Mobilization",
    category: "mobility",
    isAnchor: false,
    equipment: ["bodyweight"],
    muscles: ["foot", "ankle"],
    defaultSets: 1,
    defaultReps: "10",
    notes: "Joe's PT. Each side. Keeps the foot supple and ready to load.",
  },
  {
    id: "ex_yielding_hip",
    name: "Yielding Hip Exercises",
    category: "mobility",
    isAnchor: false,
    equipment: ["bodyweight"],
    muscles: ["hip_flexors", "adductors"],
    defaultSets: 1,
    defaultReps: "10",
    notes: "Joe's PT. Each side.",
  },
  {
    id: "ex_knee_extensions",
    name: "Knee Extensions",
    category: "mobility",
    isAnchor: false,
    equipment: ["bodyweight"],
    muscles: ["quads"],
    defaultSets: 1,
    defaultReps: "15",
    notes: "Joe's PT. Slow and full range. Quad rehab and activation.",
  },
  {
    id: "ex_calf_raises",
    name: "Calf Raises",
    category: "mobility",
    isAnchor: false,
    equipment: ["bodyweight", "step"],
    muscles: ["calves"],
    defaultSets: 3,
    defaultReps: "20",
    notes: "On step for full range. Slow and controlled. PF rehab and calf strengthening.",
  },
  {
    id: "ex_single_leg_calf_raises",
    name: "Single-Leg Calf Raises",
    category: "mobility",
    isAnchor: false,
    equipment: ["bodyweight", "step"],
    muscles: ["calves"],
    defaultSets: 3,
    defaultReps: "15",
    notes: "Each side. On step. More load than bilateral. Key for plantar fasciitis rehab.",
  },
  {
    id: "ex_plantar_fascia_stretch",
    name: "Plantar Fascia Stretch",
    category: "mobility",
    isAnchor: false,
    equipment: ["bodyweight"],
    muscles: ["plantar_fascia", "foot"],
    defaultSets: 1,
    defaultReps: "60 sec",
    notes: "Each foot. Toe extension against floor or wall. Do this before getting out of bed too.",
  },
  {
    id: "ex_banded_ankle_dorsiflexion",
    name: "Banded Ankle Dorsiflexion",
    category: "mobility",
    isAnchor: false,
    equipment: ["band"],
    muscles: ["ankle"],
    defaultSets: 1,
    defaultReps: "15",
    notes: "Each side. Band around rack at ankle height. Drive knee forward over toe. Great for squat depth.",
  },
  {
    id: "ex_towel_toe_scrunches",
    name: "Towel Toe Scrunches",
    category: "mobility",
    isAnchor: false,
    equipment: ["bodyweight"],
    muscles: ["foot"],
    defaultSets: 1,
    defaultReps: "30",
    notes: "Curl towel with toes. PF foot strengthening. Can do seated while working.",
  },
  {
    id: "ex_pigeon_pose",
    name: "Pigeon Pose",
    category: "mobility",
    isAnchor: false,
    equipment: ["bodyweight"],
    muscles: ["hips", "glutes", "piriformis"],
    defaultSets: 1,
    defaultReps: "90 sec",
    notes: "Each side. Fold forward for a deeper stretch. Staple cool-down after any lifting session.",
  },
  {
    id: "ex_down_dog",
    name: "Down Dog",
    category: "mobility",
    isAnchor: false,
    equipment: ["bodyweight"],
    muscles: ["hamstrings", "calves", "shoulders"],
    defaultSets: 1,
    defaultReps: "60 sec",
    notes: "Pedal heels alternately. Spread fingers wide. Great warm-up for hinge days.",
  },
  {
    id: "ex_cat_cow",
    name: "Cat-Cow",
    category: "mobility",
    isAnchor: false,
    equipment: ["bodyweight"],
    muscles: ["spine", "core"],
    defaultSets: 1,
    defaultReps: "10",
    notes: "Inhale on cow (sag), exhale on cat (round). Spinal warm-up for every session.",
  },
  {
    id: "ex_supine_twist",
    name: "Supine Twist",
    category: "mobility",
    isAnchor: false,
    equipment: ["bodyweight"],
    muscles: ["spine", "hips"],
    defaultSets: 1,
    defaultReps: "60 sec",
    notes: "Each side. Keep shoulders flat on the floor. Great cool-down after squats or deadlifts.",
  },
  {
    id: "ex_childs_pose",
    name: "Child's Pose",
    category: "mobility",
    isAnchor: false,
    equipment: ["bodyweight"],
    muscles: ["back", "hips"],
    defaultSets: 1,
    defaultReps: "60 sec",
    notes: "Arms extended or alongside body. Breathe into the back. Universal cool-down.",
  },
  {
    id: "ex_foam_rolling",
    name: "Foam Rolling",
    category: "mobility",
    isAnchor: false,
    equipment: ["foam_roller"],
    muscles: ["calves", "hamstrings", "thoracic_spine", "lats"],
    defaultSets: 1,
    defaultReps: "60 sec",
    notes: "Calves, hamstrings, IT band, thoracic spine, lats. Pause on tender spots. Great pre-session.",
  },
  {
    id: "ex_concept2_row",
    name: "Concept2 Row",
    category: "mobility",
    isAnchor: false,
    equipment: ["rower"],
    muscles: ["full_body", "cardio"],
    defaultSets: 1,
    defaultReps: "20 min",
    notes: "Easy recovery pace OR sprint intervals (30 sec on / 2 min off × 8–10 rounds). Two totally different sessions.",
  },

];

// ─── Helper functions ─────────────────────────────────────────────────────────

/** Get all exercises in a category */
export const byCategory = (cat) =>
  EXERCISES.filter((e) => e.category === cat);

/** Get all anchor lifts */
export const anchors = () =>
  EXERCISES.filter((e) => e.isAnchor);

/** Get anchor lifts for a specific category */
export const anchorsByCategory = (cat) =>
  EXERCISES.filter((e) => e.category === cat && e.isAnchor);

/** Get accessories for a specific category (non-anchor) */
export const accessoriesByCategory = (cat) =>
  EXERCISES.filter((e) => e.category === cat && !e.isAnchor);

/** Get exercise by ID */
export const byId = (id) =>
  EXERCISES.find((e) => e.id === id);

/** Get swap candidates — same category, not the current exercise */
export const swapOptions = (exerciseId) => {
  const ex = byId(exerciseId);
  if (!ex) return [];
  return EXERCISES.filter((e) => e.category === ex.category && e.id !== exerciseId);
};

// ─── Category metadata ────────────────────────────────────────────────────────

export const CATEGORIES = [
  { id: "squat",    emoji: "🏋️", label: "Squat",    desc: "Back squat · front squat · variations" },
  { id: "hinge",    emoji: "⚡",  label: "Hinge",    desc: "Deadlift · RDL · glute work" },
  { id: "press",    emoji: "💪",  label: "Press",    desc: "Bench · OHP · push accessories" },
  { id: "pull",     emoji: "🫷",  label: "Pull",     desc: "Rows · ring rows · pull-ups · curls" },
  { id: "core",     emoji: "🔥",  label: "Core",     desc: "Carries · anti-rotation · stability" },
  { id: "mobility", emoji: "🌸",  label: "Mobility", desc: "PT · stretching · warm-up · cool-down" },
];

// ─── Session templates ────────────────────────────────────────────────────────
// These define the structure of each session type.
// The app picks exercises from the database to fill each slot.

export const SESSION_TEMPLATES = [
  {
    id: "session_a",
    name: "Squat",
    anchorCategory: "squat",
    slots: [
      { category: "squat",    isAnchor: true,  label: "Main lift" },
      { category: "press",    isAnchor: false, label: "Accessory press" },
      { category: "pull",     isAnchor: false, label: "Accessory pull" },
      { category: "core",     isAnchor: false, label: "Core" },
    ],
  },
  {
    id: "session_b",
    name: "Hinge",
    anchorCategory: "hinge",
    slots: [
      { category: "hinge",    isAnchor: true,  label: "Main lift" },
      { category: "squat",    isAnchor: false, label: "Accessory squat" },
      { category: "press",    isAnchor: false, label: "Accessory press" },
      { category: "core",     isAnchor: false, label: "Core" },
    ],
  },
  {
    id: "session_c",
    name: "Press",
    anchorCategory: "press",
    slots: [
      { category: "press",    isAnchor: true,  label: "Main lift" },
      { category: "pull",     isAnchor: false, label: "Accessory pull" },
      { category: "squat",    isAnchor: false, label: "Accessory squat" },
      { category: "core",     isAnchor: false, label: "Core" },
    ],
  },
  {
    id: "session_d",
    name: "Pull",
    anchorCategory: "pull",
    slots: [
      { category: "pull",     isAnchor: true,  label: "Main lift" },
      { category: "hinge",    isAnchor: false, label: "Accessory hinge" },
      { category: "press",    isAnchor: false, label: "Accessory press" },
      { category: "core",     isAnchor: false, label: "Core" },
    ],
  },
];
